---
name: lab-07
break: true
indent: 4
---

src/main/java/labseven:
    HumanQuest.java:
        ConfirmFileExists
        CountSingleLineComments --language Java --count 9
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
        MatchFileFragment --fragment "import java.util.Scanner;" --count 1 --exact
        MatchFileFragment --fragment ".nextInt()" --count 1 --exact
        MatchFileFragment --fragment ".nextLine()" --count 1 --exact
        MatchFileFragment --fragment "new Die(" --count 5 --exact
        MatchFileFragment --fragment ".roll()" --count 5 --exact
        MatchFileFragment --fragment ".getRoll()" --count 5 --exact
        MatchFileFragment --fragment "boolean" --count 1
        
src/main/java/labseven:
    Die.java:
        ConfirmFileExists
        MatchFileFragment --fragment "TODO" --count 0 --exact
        MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
        MatchFileFragment --fragment "this.sides" --count 2
        MatchFileFragment --fragment "this.result" --count 3 --exact
        MatchFileFragment --fragment "public String toString()" --count 1 --exact
        MatchFileFragment --fragment "this.random" --count 2
        MatchFileFragment --fragment "(int sides)" --count 1 --exact

writing:
    reflection.md:
        ConfirmFileExists
        mdl --rules ~MD009,~MD012,~MD014,~MD013,~MD022,~MD026,~MD031
        CountFileWords --count 350
        CountFileParagraphs --count 7
        MatchFileFragment --fragment "TODO" --count 0 --exact
        CountMarkdownTags --tag "code_block" --count 1 --exact
        MatchFileFragment --fragment "{YOUR NAME HERE}" --count 0 --exact
        
CountCommits --count 3
ExecuteCommand --command "gradle build"